export const SET_CHANNEL_INFO = 'SET_CHANNEL_INFO';
export const SET_TICKER_DATA = 'SET_TICKER_DATA';
export const SET_ORDER_BOOK_DATA = 'SET_ORDER_BOOK_DATA';
export const UPDATE_ORDER_BOOK_DATA = 'UPDATE_ORDER_BOOK_DATA';
export const REMOVE_ORDER_BOOK_DATA = 'REMOVE_ORDER_BOOK_DATA';
export const SET_TRADE_DATA = 'SET_TRADE_DATA';
export const UPDATE_TRADE_DATA = 'UPDATE_TRADE_DATA';
